# Generated by Django 4.1.6 on 2023-02-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_rating_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='world_premiere',
            field=models.DateTimeField(default=0, verbose_name='Примьера в мире'),
        ),
    ]
